# This is a basic workflow to help you get started with Actions

name: Build and deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch: {}
  push:
    branches:
    - main
    paths:
      - '*/**.go'
      - '*/**.html'
      - Dockerfile
      - 'go.*'

      # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/setup-go@v3
        with:
          go-version: ^1.18

      - uses: actions/checkout@v3
        with:
          fetch-depth: '1'

      - name: Install dependencies
        run: |
          go get -v -t -d ./...

      - name: Run test build
        run: go build -a -installsuffix cgo -o service .

      - name: Github Tag Bump
        id: bump_version
        uses: anothrNick/github-tag-action@18284c78f6ac68868d5341f57c4f971fb5b7605c # 1.34.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          RELEASE_BRANCHES: main
          WITH_V: true

      - run: echo "tag=ghcr.io/oslokommune/log-output-generator" >> $GITHUB_ENV
        id: tag_store
      - run: echo "version=$(git describe --tags `git rev-list --tags --max-count=1`)" >> $GITHUB_ENV
        id: version_store

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ env.tag }}:${{ env.version }}
